#%RAML 1.0
title: Inventory System API
mediaType:
  - application/json
version: "1.0"
protocols:
  - HTTP
/inventory:
  get:
    description: Retrieve all inventory items
    responses:
      "200":
        body:
          items:
            type: InventoryItem
  post:
    description: Add a new inventory item
    body:
      type: InventoryItem
    responses:
      "201":
        description: Inventory item created
        body:
          type: InventoryItem
      "401":
        description: Unauthorised
      "409":
        description: Inventory item already exists
      "500":
        description: Internal server error
baseUri: http://localhost/api
/inventory/{productCode}:
  put:
    description: Update existing inventory item
    body:
      type: InventoryItem
    responses:
      "200":
        description: Inventory item updated successfully
        body:
          type: InventoryItem
      "204":
        description: Inventory item not found
      "304":
        description: Inventory item not modified
      "404":
        description: Inventory item not found
      "500":
        description: Internal server error
  get:
    description: Retrieve single inventory item
    responses:
      "200":
        body:
          type: InventoryItem
      "204":
        description: Inventory item not found
      "404":
        description: Inventory item not found
      "500":
        description: Internal server error
  delete:
    description: Delete existing inventory item
    responses:
      "200":
        description: Inventory item deleted successfully
      "204":
        description: Inventory item not found
      "404":
        description: Inventory item not found
      "500":
        description: Internal server error
types:
  InventoryItem:
    properties:
      productCode:
        description: Product Code
        example: TSHIRT-0099
        type: string
      size:
        description: Product size
        enum:
          - XS
          - S
          - M
          - L
          - XL
          - XXL
          - NA
        example: L
        type: string
      description:
        description: Product description
        example: API Ninja
        type: string
      count:
        description: Item count
        example: 42
        type: number
        format: int
